import Footer from "../compoment/home_page/Footer";
import Header from "../compoment/home_page/Header";
import "../styles/globals.css";
import { Provider } from "react-redux";
import { store } from "../store/store";
import Head from "next/head";
function MyApp({ Component, pageProps }) {
  return (
    <>
      <Head>
        <title>Manh D.Vu</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
        <link
          href="https://fonts.googleapis.com/css2?family=Outfit:wght@300;400;500&family=Poppins:wght@500&display=swap"
          rel="stylesheet"
        />
        <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.5.1/jquery.min.js"></script>
      </Head>
      <Provider store={store}>
          <Header></Header>
          <Component {...pageProps} />
          <Footer></Footer>
      </Provider>
    </>
  );
}

export default MyApp;
